config/routes.rb
Rails.application.routes.draw do

  get '/confirmation' => 'pages#confirmation'
  get '/how_it_works' => 'pages#how_it_works'

  root      'deals#index'
  get       'signup'  => 'users#new'
  get       'login'   => 'sessions#new'
  post      'login'   => 'sessions#create'
  delete    'logout'  => 'sessions#destroy'

  resources :users do
    resources :deals
  end

  resources :deals do
    resources :orders
  end

  resources :charges

end

app/models/deal.rb
class Deal < ActiveRecord::Base
  has_attached_file :image, styles: { :medium => "500x500" }
  validates_attachment_content_type :image, content_type: ['image/png', 'image/jpg', 'image/jpeg', 'image/gif']
  belongs_to :organizer, foreign_key: "user_id", class_name: "User"
  has_many   :orders, dependent: :destroy
  has_many   :buyers, through: :orders

  accepts_nested_attributes_for :orders

  validates         :url, presence: true


  monetize :wholesale_price_cents
  monetize :retail_price_cents

  require 'open-uri'

  def self.search(params)
    url = params.split("#")[0].to_s
    response = HTTParty.get(url)
    dom = Nokogiri::HTML(response.body)
  end

  def image_from_url(url)
    self.image = URI.parse(url)
  end

end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :update, :new, :edit]
  skip_before_action :verify_authenticity_token

  def index
    @user = User.new
    @deals = Deal.all
    @deal = Deal.new
  end

  def new
    if params[:search]
      @response = Deal.search(params[:search])
    end
    @deal = Deal.new
    @deal.orders.build
    @user = User.new
  end

  def edit
    correct_user
    @user = current_user
  end

  def update
    correct_user
    if @deal.update(deal_params)
      flash[:success] = "Deal successfully updated!"
      redirect_to @current_user
    else
      render 'edit'
    end
  end

  def show
    @deal = Deal.find(params[:id])
    @user = User.new
  end

  def create
    @deal = current_user.deals.new(deal_params)
    @deal.deal_expiration = 30.days.from_now
    @deal.wholesale_price = @deal.wholesale_price_cents
    @deal.retail_price = @deal.retail_price_cents
    @deal.total_bids = 0

    @order = Order.new(stripe_params)

    if @deal.save
      flash[:success] = "You've created a new deal!"
      @order.process_payment
      @order.user_id = current_user.id
      @order.deal_id = @deal.id
      if @order.save
        redirect_to @current_user
      else
        flash[:danger] = "Your payment was unsuccessful."
        @deal.destroy
      end
    else
      render 'new'
    end
  end

  def destroy
    @deal = current_user.deals.find_by(id: params[:id])
    # if @current_user.id != @deal.user_id
    #   flash[:danger] = "You are not authorized."
    #   redirect_to root_url
    # end
    @deal.destroy
    flash[:success] = "Deal deleted."
    redirect_to @current_user || root_url
  end


  private

  def set_deal
    @deal = Deal.find(params[:id])
  end

  def deal_params
    params.require(:deal).permit(:url, :title, :retail_price_cents, :wholesale_price_cents, :image, :delivery_method, :minimum_bids, :estimated_delivery, :description)
  end

  def stripe_params
    params.permit :stripeEmail, :stripeToken
  end

  def correct_user
    @deal = current_user.deals.find_by(id: params[:id])
    redirect_to root_url if @deal.nil?
  end

end

app/helpers/deals_helper.rb
module DealsHelper
  def title
    @response.css("#productdisplayForm > div > div > div.col-left-inner > div > div.hinfo.clearfix > h1").text
  end

  def price_range
    @response.css("#js-priceTips > span:nth-child(2)").text
  end

  def description
    @response.css("#itemDescription > div.description > ul > li:nth-child(1)").text
  end

  def image
    @response.css("#firstBImage > span > img")[0].to_a[1][1]
  end

  def sorted_deals
    @deals = @deals.sort_by &:created_at
    @deals.reverse!
  end
end

app/views/deals/_edit_form.html.erb
<div class="manual-deal">
  <%= form_for(@deal, remote: true) do |f| %>
    <%= render 'shared/error_messages_deal' %>

    <%= f.label :url %><br>
    <%= f.url_field :url %><br><br>

    <%= f.label :title %><br>
    <%= f.text_field :title %><br><br>

    <%= f.label :image %><br>
    <%= f.file_field :image %><br><br>

    <%= f.label :retail_price_cents %><br>
    <%= f.text_field :retail_price_cents %><br><br>

    <%= f.label :wholesale_price_cents %><br>
    <%= f.text_field :wholesale_price_cents %><br><br>

    <%= f.label :minimum_bids %><br>
    <%= f.number_field :minimum_bids %><br><br>

    <%= f.label :estimated_delivery %><br>
    <%= f.date_field :estimated_delivery %><br><br>

    <%= f.label :delivery_method %><br>
    <%= f.select :delivery_method, ['Delivery', 'Local Pickup'] %><br><br>

    <%= f.label :description %><br>
    <%= f.text_area :description %><br>
    <%= f.submit "Edit Deal", class: "edit-button" %>
    <% end %>
</div>

app/views/deals/_form.html.erb
<div class="manual-deal">
  <%= form_for(@deal) do |f| %>
    <%= render 'shared/error_messages_deal' %>

    <%= f.label :url %><br>
    <%= f.url_field :url %><br><br>

    <%= f.label :title %><br>
    <%= f.text_field :title %><br><br>

    <%= f.label :image %><br>
    <%= f.file_field :image %><br><br>

    <%= f.label :retail_price_cents %><br>
    <%= f.text_field :retail_price_cents %><br><br>

    <%= f.label :wholesale_price_cents %><br>
    <%= f.text_field :wholesale_price_cents %><br><br>

    <%= f.label :minimum_bids %><br>
    <%= f.number_field :minimum_bids %><br><br>

    <%= f.label :estimated_delivery %><br>
    <%= f.date_field :estimated_delivery %><br><br>

    <%= f.label :delivery_method %><br>
    <%= f.select :delivery_method, ['Delivery', 'Local Pickup'] %><br><br>

    <%= f.label :description %><br>
    <%= f.text_area :description %><br>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="Charge"
            data-amount="<%=@deal.wholesale_price_cents%>">
    </script>
    <% end %>
</div>

app/views/deals/_scrape_form.html.erb
<div class="manual-deal">
  <%= form_for(@deal, multipart: true) do |f| %>
    <%= render 'shared/error_messages_deal' %>

    <%= f.label :url, "Original Deal URL" %>
    <%= f.url_field :url, value: params[:search] %><br><br>

    <%= f.label :title %>
    <%= f.text_field :title, value: title %><br><br>

    <%= f.label :image %>
    <%= f.text_field :image, value: image %><br><br>

    <%= f.label :retail_price_cents, "Retail Price" %>
    <%= f.text_field :retail_price_cents %><br><br>

    <%= f.label :wholesale_price_cents, "Wholesale Price" %>
    <%= f.text_field :wholesale_price_cents, value: price_range %><br><br>

    <%= f.label :minimum_bids %>
    <%= f.number_field :minimum_bids %><br><br>

    <%= f.label :estimated_delivery %>
    <%= f.date_field :estimated_delivery %><br><br>

    <%= f.label :delivery_method %>
    <%= f.select :delivery_method, ['Delivery', 'Local Pickup'] %><br><br>

    <%= f.label :description %>
    <%= f.text_area :description, value: description %><br>

    <h3 id="step-3"> <u>Step 3</u>: Pay for your order: </h3>
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="Charge"
            data-amount="<%=@deal.wholesale_price_cents%>">
    </script>
  <% end %>
</div>

app/views/deals/edit.html.erb
<%= provide(:title, "Edit Deal") %>
<h1>Edit Deal</h1>
<div>
<%= render 'edit_form' %>
</div>
<br>
<%= link_to 'Delete deal', deal_path, class: "delete-link", method: :delete, data: { confirm: 'Are you sure you want to destroy this deal?'} %>

app/views/deals/index.html.erb
<%= provide(:title, "Deals") %>

<% if current_user %>
  <button class="create-button"><%= link_to "Create A Deal!", new_deal_path %></button>
<% else %>
  <button class="create-button trigger"><span class="create-text">Create A Deal!</span></button>
<% end %>

<h3>Latest Deals</h3>
<div class="wrapper">
  <% sorted_deals.each do |deal| %>
  <div class="deal-box">
    <figcaption>
      <%= link_to image_tag(deal.image), deal %>
      <h2><%= link_to(truncate(deal.title, length: 30, seperator: ' '), deal)  %></h2>
      <div class="deal-detail">
        <div class="prices">
          <span class="retail">$<%= deal.retail_price %></span>
          |   <span class="wholesale">$<%= deal.wholesale_price %></span><br><br>
        </div>
        <div class="progress-meter">
        	<span class="progress" style="width: <%= number_to_percentage(progress( deal.total_bids, deal.minimum_bids), precision: 0) %>;"></span>
        </div>
        Progress: <%= number_to_percentage(progress( deal.total_bids, deal.minimum_bids), precision: 0) %><br>
        Time Remaining: <%= ((deal.deal_expiration - Time.now) / 86400).to_i.to_s %> days
      </div>
    </figcaption>
  </div>
  <% end %>
</div>

app/views/deals/new.html.erb
<%= provide(:title, "New Deal") %>
<h2>Create a New Deal</h2>

<% if params[:search] && params[:search].present? %>
  <h3><u>Step 2</u>:  Complete the missing fields. All fields required.</h3>
  <%= render 'scrape_form' %>
<% else %>
  <h3><u>Step 1</u>:  Enter the wholesale URL and click "Add Deal" button:</h3>
  <div class="search-form">
    <%= form_tag new_deal_path, id: "search-form", method: :get do %>
      <%= label_tag(:search, "Enter the URL:") %>
      <%= text_field_tag :search, params[:search] %>
      <%= button_tag(type: 'submit', name: nil, class: "create-button", id: "scrape-trigger") do %>
        <span class="create-text">Add Deal</span>
      <% end %>
    <% end %>
  </div>
<% end %>

<%#= submit_tag "Add Deal", name: nil, class: "create-button create-text", id: "scrape-trigger" %>

app/views/deals/show.html.erb
<% provide(:title, "Deal Detail") %>
<div class="deal-wrapper">
  <div class="deal-image">
    <%= image_tag @deal.image, class: "show-image" %>
  </div>
  <div class="conditional-text">
    <% if logged_in? %>
      <% if current_user.id == @deal.organizer.id %>
        <button class="join-button deal"><%= link_to 'Edit This Deal', edit_deal_path %></button>
      <% elsif current_user.orders.find_by(deal_id: @deal.id) %>
        <h2>You already joined this deal!</h2>
      <% else %>
        <button class="join-button deal"><%= link_to "Join this deal!", new_deal_order_path(@deal.id) %></button>
      <% end %>
    <% else %>
        <button class="join-button deal"><span class="create-text trigger">Join this deal!</span></button>
    <% end %>
  </div>
  <div class="deal-text">
    <h2 class="deal-title"><%= @deal.title %></h2>
    <span class="retail">$<%= @deal.retail_price %></span>
    |   <span class="wholesale">$<%= @deal.wholesale_price %></span><br><br>
    <div class="progress-meter">
      <span class="progress" style="width: <%= number_to_percentage(progress( @deal.total_bids, @deal.minimum_bids), precision: 0) %>;"></span>
    </div>
    <strong>Progress:&nbsp;&nbsp;</strong> <%= number_to_percentage(progress( @deal.total_bids, @deal.minimum_bids), precision: 0) %><br>
    <strong>Time Remaining:&nbsp;&nbsp;</strong>  <%= ((@deal.deal_expiration - Time.now) / 86400).to_i.to_s %> days<br><br>
  </div>
  <div class="description-text">
    <strong>Organizer:&nbsp;&nbsp;</strong>  <%= @deal.organizer.first_name.capitalize %><br>
    <strong>Expiration:&nbsp;&nbsp;</strong>  <%= l @deal.deal_expiration, format: :long %><br>
    <strong>Estimated Delivery:&nbsp;&nbsp;</strong>  <%= l @deal.estimated_delivery, format: :long %><br>
    <strong>Original Deal:&nbsp;&nbsp;</strong>  <%= link_to @deal.url %><br><br><br>
    <strong>Description:&nbsp;&nbsp;</strong> <br><br> <%= @deal.description %><br><br>
    <h3 class="viral">Make it go viral!</h3>
    <ul class="rrssb-buttons">
      <li class="rrssb-facebook">
        <a href="https://www.facebook.com/sharer/sharer.php?u=http://thebulk.co/deals/params:[id]" class="popup">
          <span class="rrssb-icon">
            <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" width="29" height="29" viewBox="0 0 29 29">
              <path d="M26.4 0H2.6C1.714 0 0 1.715 0 2.6v23.8c0 .884 1.715 2.6 2.6 2.6h12.393V17.988h-3.996v-3.98h3.997v-3.062c0-3.746 2.835-5.97 6.177-5.97 1.6 0 2.444.173 2.845.226v3.792H21.18c-1.817 0-2.156.9-2.156 2.168v2.847h5.045l-.66 3.978h-4.386V29H26.4c.884 0 2.6-1.716 2.6-2.6V2.6c0-.885-1.716-2.6-2.6-2.6z"
              class="cls-2" fill-rule="evenodd" />
            </svg>
          </span>
          <span class="rrssb-text">facebook</span>
        </a>
      </li>
      <li class="rrssb-twitter">
        <!-- Replace href with your Meta and URL information  -->
        <a href="https://twitter.com/intent/tweet?text=The%20Bulk%20!"
        class="popup">
          <span class="rrssb-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 28 28">
              <path d="M24.253 8.756C24.69 17.08 18.297 24.182 9.97 24.62c-3.122.162-6.22-.646-8.86-2.32 2.702.18 5.375-.648 7.507-2.32-2.072-.248-3.818-1.662-4.49-3.64.802.13 1.62.077 2.4-.154-2.482-.466-4.312-2.586-4.412-5.11.688.276 1.426.408 2.168.387-2.135-1.65-2.73-4.62-1.394-6.965C5.574 7.816 9.54 9.84 13.802 10.07c-.842-2.738.694-5.64 3.434-6.48 2.018-.624 4.212.043 5.546 1.682 1.186-.213 2.318-.662 3.33-1.317-.386 1.256-1.248 2.312-2.4 2.942 1.048-.106 2.07-.394 3.02-.85-.458 1.182-1.343 2.15-2.48 2.71z"
              />
            </svg>
          </span>
          <span class="rrssb-text">twitter</span>
        </a>
      </li>
      <li class="rrssb-googleplus">
        <!-- Replace href with your meta and URL information.  -->
        <a href="https://plus.google.com/share?url=Check%20out%20The%20Bulk!%20http://thebulk.co/deals" class="popup">
          <span class="rrssb-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 28 28">
              <path d="M14.703 15.854l-1.22-.948c-.37-.308-.88-.715-.88-1.46 0-.747.51-1.222.95-1.662 1.42-1.12 2.84-2.31 2.84-4.817 0-2.58-1.62-3.937-2.4-4.58h2.098l2.203-1.384h-6.67c-1.83 0-4.467.433-6.398 2.027C3.768 4.287 3.06 6.018 3.06 7.576c0 2.634 2.02 5.328 5.603 5.328.34 0 .71-.033 1.083-.068-.167.408-.336.748-.336 1.324 0 1.04.55 1.685 1.01 2.297-1.523.104-4.37.273-6.466 1.562-1.998 1.187-2.605 2.915-2.605 4.136 0 2.512 2.357 4.84 7.288 4.84 5.822 0 8.904-3.223 8.904-6.41.008-2.327-1.36-3.49-2.83-4.73h-.01zM10.27 11.95c-2.913 0-4.232-3.764-4.232-6.036 0-.884.168-1.797.744-2.51.543-.68 1.49-1.12 2.372-1.12 2.807 0 4.256 3.797 4.256 6.24 0 .613-.067 1.695-.845 2.48-.537.55-1.438.947-2.295.95v-.003zm.032 13.66c-3.62 0-5.957-1.733-5.957-4.143 0-2.408 2.165-3.223 2.91-3.492 1.422-.48 3.25-.545 3.556-.545.34 0 .52 0 .767.034 2.574 1.838 3.706 2.757 3.706 4.48-.002 2.072-1.736 3.664-4.982 3.648l.002.017zM23.254 11.89V8.52H21.57v3.37H18.2v1.714h3.367v3.4h1.684v-3.4h3.4V11.89"
              />
            </svg>
          </span>
          <span class="rrssb-text">google+</span>
        </a>
      </li>
      <li class="rrssb-pinterest">
        <!-- Replace href with your meta and URL information.  -->
        <a href="http://pinterest.com/pin/create/button/?url=http://thebulk.co/deals&amp;description=Chck%20out%20The%20Bulk!">
          <span class="rrssb-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 28 28">
              <path d="M14.02 1.57c-7.06 0-12.784 5.723-12.784 12.785S6.96 27.14 14.02 27.14c7.062 0 12.786-5.725 12.786-12.785 0-7.06-5.724-12.785-12.785-12.785zm1.24 17.085c-1.16-.09-1.648-.666-2.558-1.22-.5 2.627-1.113 5.146-2.925 6.46-.56-3.972.822-6.952 1.462-10.117-1.094-1.84.13-5.545 2.437-4.632 2.837 1.123-2.458 6.842 1.1 7.557 3.71.744 5.226-6.44 2.924-8.775-3.324-3.374-9.677-.077-8.896 4.754.19 1.178 1.408 1.538.49 3.168-2.13-.472-2.764-2.15-2.683-4.388.132-3.662 3.292-6.227 6.46-6.582 4.008-.448 7.772 1.474 8.29 5.24.58 4.254-1.815 8.864-6.1 8.532v.003z"
              />
            </svg>
          </span>
          <span class="rrssb-text">pinterest</span>
        </a>
      </li>
    </ul>
  </div>
</div>