config/routes.rb
Rails.application.routes.draw do

  get '/confirmation' => 'pages#confirmation'
  get '/how_it_works' => 'pages#how_it_works'

  root      'deals#index'
  get       'signup'  => 'users#new'
  get       'login'   => 'sessions#new'
  post      'login'   => 'sessions#create'
  delete    'logout'  => 'sessions#destroy'

  resources :users do
    resources :deals
  end

  resources :deals do
    resources :orders
  end

  resources :charges

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="support">
    Contact us:<br>
    Email: <%= mail_to "support@thebulk.co" %><br>
    <%= link_to "Privacy Policy", "#", class: "privacy" %>
    <span class="copy">&copy; 2015</span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= link_to image_tag('logo.png'), root_path, class: 'logo' %>
	<ul>
	  <% if current_user %>
			<li class="purple"><%= link_to "How It Works", how_it_works_path %></li>
	    <li class="purple"> Hello, <%= link_to current_user.first_name, user_path(current_user.id) %></li>
	    <li class="purple"><%= link_to "Log out", logout_path, method: "delete" %></li>
	  <% else %>
			<li class="purple"><%= link_to "How It Works", how_it_works_path %></li>
		  <li class="purple"><span class="trigger">Log in</span></li>
	    <li class="purple"><span class="trigger">Sign-up</span></li>
	  <% end %>
	</ul>
</header>
<div class="tag-line">
  Join others. Buy in bulk. Pay wholesale.
</div>
<div class="modal">
	<%= render 'sessions/form' %>
	<%= render 'users/form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults, 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</head>
<body>
  <div class="overlay"></div>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
  </div>

<%= yield %>


<script src="https://checkout.stripe.com/checkout.js"></script>